first-iterration
FausT-VX/sprint8-go-db-sql-final pull request #1
Opened 2024-05-25 12:03 UTC by FausT-VX

2024-05-25 12:52 UTC, dirtymew requested changes
Привет Антон

хорошая работа - но есть что доработать

см PR

2024-05-25 12:52 UTC, dirtymew commented on parcel.go
> +	}
тут забыл закрыть курсор

2024-05-25 12:52 UTC, dirtymew commented on parcel.go
>  	return res, nil
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-05-25 12:52 UTC, dirtymew commented on parcel.go
> +	_, err := s.db.Exec("UPDATE parcel SET address = :address WHERE number = :number AND status = :reg_status",
тут отлично - все одним запросом

2024-05-25 12:52 UTC, dirtymew commented on parcel_test.go
> +	if err != nil {
условие лишнее и бессмысленное  просто require.NoError(t, err) - ну если конечно не платят за строчки кода))

2024-05-25 12:52 UTC, dirtymew commented on parcel_test.go
> +	if err != nil {
тут тоже не нужно условие - просто require.NoError(t, err)

2024-05-25 12:52 UTC, dirtymew commented on parcel_test.go
> +	require.ErrorIs(t, err, sql.ErrNoRows)
тут я бы рекомендовал так
require.Error(t, err)
assert.ErrorIs(t, err, sql.ErrNoRows)

2024-05-25 12:52 UTC, dirtymew commented on parcel_test.go
> +		assert.EqualValues(t, p, parcel)
просто Equal

2024-05-25 12:52 UTC, dirtymew commented on parcel_test.go
>  	for _, parcel := range storedParcels {
тут можно лучше в testify есть функции для работы с массивами - можно обойтись без цикла и мапы тут и все проверить одним assert-ом

2024-05-25 12:53 UTC, dirtymew commented
> _ No description provided. _

@FausT-VX - случайно принял работу ((( 

если есть вопросы по ревью и/или как поправишь - тегни меня в комментарии я посмотрю

2024-05-25 12:56 UTC, FausT-VX commented on parcel_test.go
> +	if err != nil {
:) тоже так подумал, и сделал, но в промежуточных заданиях в "эталонном" коде, с которыми нужно было сверяться, почему-то были эти условия

2024-05-25 12:57 UTC, dirtymew commented on parcel_test.go
> +	if err != nil {
там скорее всего нужно подправить... в общем так не стоит писать тесты - они сильно хуже читаются

2024-05-25 15:35 UTC, FausT-VX commented on parcel.go
>  	return res, nil
> нужно еще ошибку из rows обработать http://go-database-sql.org/errors.html

А при ошибке как лучше возвращать:
так:          return []Parcel{}, err
или так:   return nil, err
Или без разницы?

2024-05-25 15:38 UTC, FausT-VX commented on parcel.go
> +	_, err := s.db.Exec("UPDATE parcel SET address = :address WHERE number = :number AND status = :reg_status",
> тут отлично - все одним запросом

Так еще в 1С научили году в 2007-2008 :) получать в запросах максимально готовый результат, потом лет 13 работа с MS SQL Reporting Services, так что запросы мой конек :)

2024-05-25 15:40 UTC, FausT-VX commented on parcel_test.go
> +	if err != nil {
> условие лишнее и бессмысленное просто require.NoError(t, err) - ну если конечно не платят за строчки кода))

Я тоже так подумал и даже сделал, но в самом спринте в "эталонном" коде, с которым предлагалось сравнить свой код, было условие, поэтому добавил :)

2024-05-25 15:42 UTC, FausT-VX commented on parcel_test.go
> +	if err != nil {
> условие лишнее и бессмысленное просто require.NoError(t, err) - ну если конечно не платят за строчки кода))

Спасибо что обратил внимание!

2024-05-25 15:50 UTC, FausT-VX commented on parcel_test.go
>  	for _, parcel := range storedParcels {
> тут можно лучше в testify есть функции для работы с массивами - можно обойтись без цикла и мапы тут и все проверить одним assert-ом

Так в прекоде была мапа и ее требовалось использовать

2024-05-25 15:52 UTC, FausT-VX commented
> > _ No description provided. _
> 
> @FausT-VX - случайно принял работу (((
> 
> если есть вопросы по ревью и/или как поправишь - тегни меня в комментарии я посмотрю

@dirtymew Поправил...

2024-05-26 12:15 UTC, dirtymew commented on parcel_test.go
>  	for _, parcel := range storedParcels {
это рекомендация - в заданиях можно отходить от прекода) в сторону улучшения...

2024-05-26 12:17 UTC, dirtymew commented on parcel.go
>  	return res, nil
О хорошо что спросил - я не заметил  return nil, err   конечно 

Разница значительная
так как []Parcel{} это не nil те не дефолное значение указателя - а проинициализированный пустой массив/слайс

2024-05-26 12:20 UTC, dirtymew approved these changes
Привет Антон

все поправил - отлично

2024-05-26 12:20 UTC, dirtymew commented on parcel_test.go
>  	for _, parcel := range storedParcels {
посмотри на assert.ElemMatch

2024-12-16 09:13 UTC, merged